# Generated by Django 4.2.6 on 2023-10-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('verification_code', models.CharField(max_length=6)),
                ('attempts_counter', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
